version: '3.7'

services:
  server:
    build: ./
    container_name: diplomCloudStorage-server
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8091:8091"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
